### ISSUE TITLE
Line users page Error

### ISSUE THREAD

**Issue by codyliou** [efigence/redmine_whoiswho#1]
line http://localhost:3000/users is Error

Started GET "/users" for 127.0.0.1 at 2015-07-29 14:27:56 +0800
Processing by UsersController#index as HTML
  Current user: cody (id=3)
Mysql2::Error: Table 'redmine_test.email_addresses' doesn't exist: SHOW FULL FIELDS FROM `email_addresses`
Completed 500 Internal Server Error in 17ms (ActiveRecord: 8.0ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine_test.email_addresses' doesn't exist: SHOW FULL FIELDS FROM `email_addresses`):
  app/controllers/users_controller.rb:53:in `index'
  lib/redmine/sudo_mode.rb:63:in`sudo_mode'

---

Started GET "/my/account" for 127.0.0.1 at 2015-07-29 14:33:29 +0800
Processing by MyController#account as HTML
  Current user: cody (id=3)
Mysql2::Error: Table 'redmine_test.email_addresses' doesn't exist: SHOW FULL FIELDS FROM `email_addresses`
  Rendered my/account.html.erb within layouts/base (6.0ms)
Completed 500 Internal Server Error in 14ms (ActiveRecord: 4.0ms)

ActionView::Template::Error (Mysql2::Error: Table 'redmine_test.email_addresses' doesn't exist: SHOW FULL FIELDS FROM `email_addresses`):
    1: <div class="contextual">
    2: <%= additional_emails_link(@user) %>
    3: <%= link_to(l(:button_change_password), {:action => 'password'}, :class => 'icon icon-passwd') if @user.change_password_allowed? %>
    4: <%= call_hook(:view_my_account_contextual, :user => @user)%>
    5: </div>
  app/helpers/users_helper.rb:46:in `additional_emails_link'
  app/views/my/account.html.erb:2:in`_app_views_my_account_html_erb___497939745_104165196'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by rlisowski** [comment]
Too old redmine. From readme "Developed and tested on Redmine 3.0.3."
